### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by vgrafe** [sandrinodimattia/nextjs-auth0-example#2]
Hi!

First of all thank you so much for this great, great example app. 

I don't see any handling of refreshing the token when it expires. Am I missing something? Should I file an issue on `auth0/nextjs-auth0` instead?

Thanks!

**Comment by sandrinodimattia** [comment]
Hi @vgrafe yes we've identified this as an advanced use cases which we definitely need to add in a next release. Please file an issue in `@auth0/nextjs-auth0` so we can pick this up in the next release (basically allowing you to store the refresh token and use it to retrieve new access tokens).

**Comment by vgrafe** [comment]
Will do, thanks!
