### ISSUE TITLE
Question: Best practices for associating data with users?

### ISSUE THREAD

**Issue by awhit012** [sandrinodimattia/nextjs-auth0-example#7]
Hi, thanks for this example with Next, its helped a lot. 

I'm trying to understand how we are meant to associate data with Auth0 users. 

In the Auth0 docs they say there should be a user_id field on the user. However, in this example the /me JSON using Google auth responds with: 

```
{
"given_name": "Name",
"family_name": "Name",
"nickname": "nickname",
"name": "Name Name",
"picture": "picurl",
"locale": "en",
"updated_at": "2019-11-10T13:46:08.043Z",
"sub": "google-oauth2|12345678912345678"
}
```

Am I meant to be using "sub" in place of user_id? Is there another way this is supposed to work? 

Thanks for your time, I know this is a basic question, just can't tell if I'm missing something.

**Comment by sandrinodimattia** [comment]
The `sub` represents the user identifier. https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
